### ISSUE TITLE
Language ppgs

### ISSUE THREAD

**Issue by BuaaAlban** [PlayVoice/VI-SVC#11]
Hi，我看您列的数据集很多，也说更多数据更有趣。
我有些问题想请教一下，或许您有比较多的经验
1.我看代码里HuBert是中文的，那假如我的target speaker是英文，这里是不是就要对应换成英文的pretrained Hubert？
2.在训练过程中，您framework图里模型HuBert/VQVAE/Speaker权重是固定住了呗?直接用固定权重的pretrained model提取（看代码是直接在dataloader读出来了）
3.但训练数据可能包含中英文，是不是要根据语言找对应的HuBert，而且Hubert的特征还要dim一样？
4.Song的数据Hubert也能识别嘛？不需要在song数据上finetune嘛?  
5.Crossdomain或者indomain 有了speech数据&song数据都会变得更好?

**Comment by MaxMax2016** [comment]
1.我看代码里HuBert是中文的，那假如我的target speaker是英文，这里是不是就要对应换成英文的pretrained Hubert？
使用中文的也是支持英文的，换成英文的肯定效果更好

2.在训练过程中，您framework图里模型HuBert/VQVAE/Speaker权重是固定住了呗?直接用固定权重的pretrained model提取（看代码是直接在dataloader读出来了）
直接用来提取的数据，这些模块没有再次训练

3.但训练数据可能包含中英文，是不是要根据语言找对应的HuBert，而且Hubert的特征还要dim一样？
见1，HuBERT是都发音的建模，中英文有很多发音通用的、这就是国际音标的依据

4.Song的数据Hubert也能识别嘛？不需要在song数据上finetune嘛?
能finetune更好，可以试试whisper的PPG特征，whisper对歌曲的识别还挺好的

5.Crossdomain或者indomain 有了speech数据&song数据都会变得更好?
speach到song效果可以，song到speach不是那么好

**Comment by BuaaAlban** [comment]
谢谢~ 那whisper也是不区分中英文吗？
关于第五条我没太看懂，是说在SVC中，target是speech做歌唱转换的时候，使用speech数据&song数据效果可以。但是target是song的时候不太好，可能最好只用song的数据？

**Comment by MaxMax2016** [comment]
whisper音频编码阶段不区分语言（PPG提取阶段），文字解码才会区分语言，它会自动去预测语言类型；
在做转换的时候，输入是song，目标发音人的训练数据可以是speech数据 or song数据;
在做转换的时候，输入是speech，目标发音人的训练语料只有song的话，转换效果不太好；
更多的测试，我也没做了~

**Comment by BuaaAlban** [comment]
感谢， 已经很有帮助了
