### ISSUE TITLE
万恶的spec缓存

### ISSUE THREAD

**Issue by splinter21** [PlayVoice/VI-SVC#5]
data_util会把spec缓存成pt文件，然后之后直接读取
假如我同一个wav文件夹，要跑不同的config-spec配置同时训练，直接打架了，总是shape是对不上的；更离谱的是，因为有phone长度的裁剪，运行训练是不会报错的
最后训出来发现infer长度不对，语义也都不对
一度怀疑人生，查了半天，发现spec和phone长度比例是我调整的新老hop_size的比例，总算得出问题所在

所以有2个问题
1、spec有必要缓存吗，pytorch-gpu求spec，很耗时吗？
2、如果要缓存的话，建议写成preprocess预处理的形式，可以存在不同的文件夹下，filelist文件里指定路径，否则每换一个config，都要在data_utils.py里面改缓存路径（而且pytorch训练可能每个epoch后都会重新读取data_utils.py文件，非常坑爹）。
在dataloader里面边缓存边训练，太脏了，显存占用开始的时候也会大幅抖动。。万一晚上睡觉前挂上，早起发现爆显存了，就亏大了。。

**Comment by dtx525942103** [comment]
很好的建议
