### ISSUE TITLE
能否用逐帧的d-vector向量作为spkid输入

### ISSUE THREAD

**Issue by splinter21** [PlayVoice/VI-SVC#6]
instead of当前的使用每个wav对d-vector均值时间维成(1,256)后再在时间轴上拉成(T,256)这样

**Comment by dtx525942103** [comment]
在操作上一定可以，效果不确定了，我也没有做过这样的实验，做实验的成本太高

**Comment by dtx525942103** [comment]
在操作上一定可以（d-vector分帧和其他模块一致），效果不确定了，我也没有做过这样的实验，做实验成本太高了

**Comment by splinter21** [comment]
> 在操作上一定可以（d-vector分帧和其他模块一致），效果不确定了，我也没有做过这样的实验，做实验成本太高了

我觉得可以考虑下trim_mean，设想实际场景从网络获取音频素材，很可能会有BGM消不干净的时间点和其他次人物乱入的时间点，干扰身份信息

**Comment by dtx525942103** [comment]
现在还只是在做 纯净的声音，歌声分离出来的语料很有挑战
