### ISSUE TITLE
The VI-Speaker in training instruction is not available

### ISSUE THREAD

**Issue by medioqrity** [PlayVoice/VI-SVC#8]
The [training instruction](https://github.com/PlayVoice/VI-SVC/blob/main/svc/README.md) mentioned VI-Speaker, and it seems like it's a private repository. Is there any alternative equivalent repositories?

**Comment by MaxMax2016** [comment]
https://github.com/mozilla/TTS/tree/master/TTS/speaker_encoder

**Comment by medioqrity** [comment]
> https://github.com/mozilla/TTS/tree/master/TTS/speaker_encoder

Thanks!
